package com.fifokit.app.domain.pro

enum class ProFeature {
    MULTIPLE_ROSTERS,
    CUSTOM_ROSTER,
    YEARLY_ROSTER,
    ADVANCED_REMINDERS,
    DETAILED_ANNUAL_EARNINGS,
    JOB_COMPARISON,
    ADVANCED_FINANCIAL_GOALS,
    SAVED_FINANCIAL_SCENARIOS
}